plugins {
    id "net.fabricmc.fabric-loom" version "${loom_version}"
    id 'maven-publish'
}

base {
    archivesName = project.archives_base_name
}
group = project.maven_group

def env = System.getenv()

version = project.mod_version
if(env.COMMIT_HASH != null) {
    version += "+${env.COMMIT_HASH}"
}

repositories {
    maven { url = "https://maven.nucleoid.xyz/" }
    maven { url = "https://maven.gegy.dev/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    implementation "xyz.nucleoid:plasmid:${project.plasmid_version}"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 25
}

java {
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}