# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Mod Properties
mod_version=4.0.0
maven_group=fr.hugman
archives_base_name=build_rush

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.2
loader_version=0.16.9
fabric_version=0.112.2+1.21.4

# check this on https://nucleoid.xyz/use/
plasmid_version=0.6.3-SNAPSHOT+1.21.4