# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Mod Properties
mod_version=4.0.0
maven_group=fr.hugman
archives_base_name=build_rush

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

fabric_api_version=0.152.2+26.2

# check this on https://nucleoid.xyz/use/
plasmid_version=0.7.2-SNAPSHOT+26.2